UrunTakipSistemi/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UrunTakipSistemi.Models.Entity;

namespace UrunTakipSistemi.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun

        DbMvcStokEntities db = new DbMvcStokEntities();
        public ActionResult Index()
        {
            var urunler = db.TblUrunler.ToList();
            return View(urunler);
        }
        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> ktg = (from x in db.TblKategori.ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.Ad,
                                            Value = x.Id.ToString()
                                        }).ToList();
            ViewBag.drop = ktg;
            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(TblUrunler p)
        {
            var ktgr = db.TblKategori.Where(x => x.Id == p.TblKategori.Id).FirstOrDefault();
            p.TblKategori = ktgr;
            db.TblUrunler.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            var urn = db.TblUrunler.Find(id);
            return View("UrunGetir", urn);
        }
    }
}

UrunTakipSistemi/Views/Urun/Index.cshtml
@using UrunTakipSistemi.Models.Entity
@model List<TblUrunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 style="text-align:center;font-size:55px;font-family:'Times New Roman';">ÜRÜNLER</h3>


<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>ÜRÜN ADI</th>
        <th>ÜRÜN MARKA</th>
        <th>ÜRÜN STOK</th>
        <th>ÜRÜN ALIŞ FİYATI</th>
        <th>ÜRÜN SATIŞ FİYATI</th>
        <th>ÜRÜN KATEGORİ</th>
        @*<th>SİL</th>
            <th>GÜNCELLE</th>*@
        <th>İŞLEMLER</th>
    </tr>

    @foreach (var urn in Model)
    {
        <tr>
            <td>@urn.Id</td>
            <td>@urn.Ad</td>
            <td>@urn.Marka</td>
            <td>@urn.Stok</td>
            <td>@urn.AlisFiyat</td>
            <td>@urn.SatisFiyat</td>
            <td>@urn.TblKategori.Ad</td>
            <td>
                <a href="/Urun/UrunSil/@urn.Id" class="btn btn-danger" style="margin-right:10px;">Sil</a>
                <a href="/Urun/UrunGetir/@urn.Id" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
    }
</table>
<a href="/Urun/YeniUrun" class="btn btn-primary">Yeni Ürün</a>

UrunTakipSistemi/Views/Urun/UrunGetir.cshtml
@model UrunTakipSistemi.Models.Entity.TblUrunler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h3 style="text-align:center;font-size:55px;font-family:'Times New Roman';margin-bottom:50px;">ÜRÜN DÜZENLEME</h3>

@using (Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post))
{

    <label>Ürün Adı</label>
    @Html.TextBoxFor(urn => urn.Ad, new { @class = "form-control" })
    <br />

    <label>Marka Adı</label>
    @Html.TextBoxFor(urn => urn.Marka, new { @class = "form-control" })
    <br />

    <label>Stok Adedi</label>
    @Html.TextBoxFor(urn => urn.Stok, new { @class = "form-control" })
    <br />

    <label>Alış Fiyatı</label>
    @Html.TextBoxFor(urn => urn.AlisFiyat, new { @class = "form-control" })
    <br />

    <label>Satış Fiyatı</label>
    @Html.TextBoxFor(urn => urn.SatisFiyat, new { @class = "form-control" })
    <br />

    <label>Kategori Adı</label>
    @Html.TextBoxFor(urn => urn.Kategori, new { @class = "form-control" })
    <br />


    @Html.HiddenFor(urn => urn.Id)
    <button class="btn btn-warning">Güncelle</button>

}

UrunTakipSistemi/Views/Urun/YeniUrun.cshtml
@model UrunTakipSistemi.Models.Entity.TblUrunler
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 style="text-align:center;font-size:55px;font-family:'Times New Roman';margin-bottom:50px;">YENİ ÜRÜN EKLEME</h3>

<form method="post">

    <label>Ürün Adını Giriniz</label>
    @Html.TextBoxFor(urn => urn.Ad, new { @class = "form-control" })
    <br />

    <label>Ürün Markasını Giriniz</label>
    @Html.TextBoxFor(urn => urn.Marka, new { @class = "form-control" })
    <br />

    <label>Ürün Stok Sayısını Giriniz</label>
    @Html.TextBoxFor(urn => urn.Stok, new { @class = "form-control" })
    <br />

    <label>Ürün Alış Fiyatını Giriniz</label>
    @Html.TextBoxFor(urn => urn.AlisFiyat, new { @class = "form-control" })
    <br />

    <label>Ürün Satış Fiyatını Giriniz</label>
    @Html.TextBoxFor(urn => urn.SatisFiyat, new { @class = "form-control" })
    <br />


    <label>Ürün Kategorisini Giriniz</label>
    @Html.DropDownListFor(ktgr => ktgr.TblKategori.Id, (List<SelectListItem>)ViewBag.drop, new { @class = "form-control" })
    <br />

    <button class="btn btn-info">Ekle</button>
</form>