UrunTakipSistemi/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UrunTakipSistemi.Models.Entity;

namespace UrunTakipSistemi.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori

        DbMvcStokEntities db = new DbMvcStokEntities();
        public ActionResult Index()
        {
            var kategoriler = db.TblKategori.ToList();
            return View(kategoriler);
        }

        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKategori(TblKategori p)
        {
            db.TblKategori.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriSil(int id)
        {
            var ktgr = db.TblKategori.Find(id);
            db.TblKategori.Remove(ktgr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.TblKategori.Find(id);
            return View("KategoriGetir",ktgr);
        }

        public ActionResult KategoriGuncelle(TblKategori k)
        {
            var ktgr = db.TblKategori.Find(k.Id);
            ktgr.Ad=k.Ad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

UrunTakipSistemi/Views/Kategori/Index.cshtml
@using UrunTakipSistemi.Models.Entity
@model List<TblKategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 style="text-align:center;font-size:55px;font-family:'Times New Roman';">KATEGORİLER</h3>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>KATEGORİ ADI</th>
        @*<th>SİL</th>
            <th>GÜNCELLE</th>*@
        <th>İŞLEMLER</th>
    </tr>

    @foreach (var ktgr in Model)
    {
        <tr>
            <td>@ktgr.Id</td>
            <td>@ktgr.Ad</td>
            <td>
                <a href="/Kategori/KategoriSil/@ktgr.Id" class="btn btn-danger" style="margin-right:10px;">Sil</a>
                <a href="/Kategori/KategoriGetir/@ktgr.Id" class="btn btn-success">Güncelle</a>
            </td>
        </tr>
    }
</table>
<a href="/Kategori/YeniKategori" class="btn btn-primary">Yeni Kategori</a>

UrunTakipSistemi/Views/Kategori/KategoriGetir.cshtml
@model UrunTakipSistemi.Models.Entity.TblKategori

@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 style="text-align:center;font-size:55px;font-family:'Times New Roman';margin-bottom:50px;">KATEGORİ DÜZENLEME</h3>

@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
    <label>Kategori Adı</label>
    @Html.TextBoxFor(ktgr => ktgr.Ad, new { @class = "form-control" })
    <br />

    @Html.HiddenFor(ktgr => ktgr.Id)
    <button class="btn btn-warning">Güncelle</button>

}

UrunTakipSistemi/Views/Kategori/YeniKategori.cshtml
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <h3 style="text-align:center;font-size:55px;font-family:'Times New Roman';margin-bottom:50px;">YENİ KATEGORİ EKLEME</h3>

    <label>Kategori Adını Giriniz</label>
    <input type="text" class="form-control" name="Ad" placeholder="Kategori Adı" />
    <br />
    <button class="btn btn-info">Ekle</button>
</form>